#!/usr/bin/env python3
"""Generate src/running/age_grade/mldr_2025.rs from RunScore AgeGrade.* files.

Dev-only script. Default crate builds do not depend on this.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "age_grade" / "2025"
OUT = ROOT / "src" / "running" / "age_grade" / "mldr_2025.rs"

METERS_PER_MILE = 1609.344

# Suffix → (meters, display label). Matches Jones/Grubb 2025 road event set.
EVENT_META: dict[str, tuple[float, str]] = {
    "1mi": (1.0 * METERS_PER_MILE, "1mi"),
    "5k": (5_000.0, "5K"),
    "6k": (6_000.0, "6K"),
    "4mi": (4.0 * METERS_PER_MILE, "4mi"),
    "8k": (8_000.0, "8K"),
    "5mi": (5.0 * METERS_PER_MILE, "5mi"),
    "10k": (10_000.0, "10K"),
    "7mi": (7.0 * METERS_PER_MILE, "7mi"),
    "12k": (12_000.0, "12K"),
    "15k": (15_000.0, "15K"),
    "10mi": (10.0 * METERS_PER_MILE, "10mi"),
    "20k": (20_000.0, "20K"),
    "hm": (21_097.5, "HM"),
    "25k": (25_000.0, "25K"),
    "30k": (30_000.0, "30K"),
    "26m": (42_195.0, "FM"),  # alias of marathon; prefer .42k if both present
    "42k": (42_195.0, "FM"),
    "50k": (50_000.0, "50K"),
    "50mi": (50.0 * METERS_PER_MILE, "50mi"),
    "100k": (100_000.0, "100K"),
    "150k": (150_000.0, "150K"),
    "100mi": (100.0 * METERS_PER_MILE, "100mi"),
    "200k": (200_000.0, "200K"),
}

MIN_AGE = 5
MAX_AGE = 99
N_AGES = MAX_AGE - MIN_AGE + 1  # 95


def parse_hms(token: str) -> float:
    parts = [int(p) for p in token.split(":")]
    if len(parts) == 3:
        h, m, s = parts
    elif len(parts) == 2:
        h = 0
        m, s = parts
    else:
        raise ValueError(f"bad time: {token!r}")
    return float(h * 3600 + m * 60 + s)


def parse_runscore(path: Path) -> tuple[float, float, list[float], list[float]]:
    open_male: float | None = None
    open_female: float | None = None
    male: dict[int, float] = {}
    female: dict[int, float] = {}

    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line:
            continue
        open_m = re.match(r"^([MF])\s+(\d+:\d+(?::\d+)?)$", line)
        if open_m and " " not in open_m.group(2):
            # Open header lines have no age column.
            secs = parse_hms(open_m.group(2))
            if open_m.group(1) == "M" and open_male is None:
                open_male = secs
            elif open_m.group(1) == "F" and open_female is None:
                open_female = secs
            continue
        fac_m = re.match(r"^([MF])\s+(\d+)\s+([0-9.]+)\s*$", line)
        if not fac_m:
            raise ValueError(f"{path.name}: unparsed line {line!r}")
        age = int(fac_m.group(2))
        factor = float(fac_m.group(3))
        if fac_m.group(1) == "M":
            male[age] = factor
        else:
            female[age] = factor

    if open_male is None or open_female is None:
        raise ValueError(f"{path.name}: missing open times")
    for sex, table in (("M", male), ("F", female)):
        missing = [a for a in range(MIN_AGE, MAX_AGE + 1) if a not in table]
        if missing:
            raise ValueError(f"{path.name}: {sex} missing ages {missing[:5]}…")
    factor_male = [male[a] for a in range(MIN_AGE, MAX_AGE + 1)]
    factor_female = [female[a] for a in range(MIN_AGE, MAX_AGE + 1)]
    return open_male, open_female, factor_male, factor_female


def fmt_arr(vals: list[float]) -> str:
    # Four decimal places matches RunScore files; keep exact float literals.
    parts = []
    for i, v in enumerate(vals):
        lit = f"{v:.4f}"
        # Trim only if representation is exact enough; prefer stable 4-dp.
        parts.append(lit)
    # Wrap for readability.
    lines = []
    for i in range(0, len(parts), 10):
        chunk = ", ".join(parts[i : i + 10])
        lines.append(f"        {chunk},")
    return "\n".join(lines)


def main() -> int:
    files = sorted(DATA.glob("AgeGrade.*"))
    if not files:
        print(f"no AgeGrade.* files in {DATA}", file=sys.stderr)
        return 1

    # Prefer .42k over .26m for the marathon meters key.
    by_meters: dict[float, tuple[str, float, float, list[float], list[float]]] = {}
    for path in files:
        suffix = path.name.split(".", 1)[1]
        if suffix not in EVENT_META:
            print(f"skip unknown suffix {suffix!r}", file=sys.stderr)
            continue
        meters, label = EVENT_META[suffix]
        open_m, open_f, fm, ff = parse_runscore(path)
        if meters in by_meters and suffix == "26m":
            continue
        by_meters[meters] = (label, open_m, open_f, fm, ff)

    events = sorted(by_meters.items(), key=lambda kv: kv[0])

    chunks: list[str] = []
    chunks.append(
        """\
// @generated by scripts/gen_age_grade.py — DO NOT EDIT.
//! Embedded USATF MLDR 2025 road age-grade tables (Alan Jones / Tom Bernhard).
//!
//! Source: `data/age_grade/2025/` (CC0-1.0). Re-run the generator after updating
//! the raw RunScore files.

#![allow(clippy::unreadable_literal, clippy::approx_constant, dead_code)]

/// One official road event: open standards and single-year factors ages 5..=99.
#[derive(Debug)]
pub struct EventTable {
    /// Event length in metres.
    pub meters: f64,
    /// Short label (for example `"5K"`, `"HM"`, `"FM"`).
    pub label: &'static str,
    /// Male open (prime) standard time in seconds.
    pub open_male: f64,
    /// Female open (prime) standard time in seconds.
    pub open_female: f64,
    /// Male age factors; index `0` is age 5, index `94` is age 99.
    pub factor_male: [f64; 95],
    /// Female age factors; index `0` is age 5, index `94` is age 99.
    pub factor_female: [f64; 95],
}

/// Youngest age present in the 2025 RunScore tables.
pub const MIN_AGE: u8 = 5;
/// Oldest age present in the 2025 RunScore tables.
pub const MAX_AGE: u8 = 99;

/// Official USATF MLDR 2025 road events, shortest to longest.
pub const EVENTS: &[EventTable] = &[
"""
    )

    for meters, (label, open_m, open_f, fm, ff) in events:
        assert len(fm) == N_AGES and len(ff) == N_AGES
        chunks.append("    EventTable {\n")
        chunks.append(f"        meters: {meters:.6f},\n")
        chunks.append(f'        label: "{label}",\n')
        chunks.append(f"        open_male: {open_m:.1f},\n")
        chunks.append(f"        open_female: {open_f:.1f},\n")
        chunks.append("        factor_male: [\n")
        chunks.append(fmt_arr(fm) + "\n")
        chunks.append("        ],\n")
        chunks.append("        factor_female: [\n")
        chunks.append(fmt_arr(ff) + "\n")
        chunks.append("        ],\n")
        chunks.append("    },\n")

    chunks.append("];\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(chunks), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(events)} events)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
